FROM oven/bun:1.3.10 AS dependencies
WORKDIR /app
COPY package.json bun.lock ./
COPY apps/web/package.json apps/web/package.json
COPY apps/api/package.json apps/api/package.json
COPY packages/contracts/package.json packages/contracts/package.json
RUN bun install --frozen-lockfile --production
COPY --chown=bun:bun apps/api ./apps/api
COPY --chown=bun:bun packages/contracts ./packages/contracts
ENV NODE_ENV=production PORT=3211
USER bun
WORKDIR /app/apps/api
EXPOSE 3211 9091
CMD ["bun", "src/index.ts"]
